### ISSUE TITLE
Fix ReadTheDocs Build Errors

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#297]
# Situation

ReadTheDocs.org gives us some strange errors:

```
Requirement already satisfied: pytz>=2015.7 in /home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx->-r docs/requirements.txt (line 2)) (2020.1)
Collecting sphinxcontrib-htmlhelp
  Downloading sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Building wheels for collected packages: sphinx-argparse
  Building wheel for sphinx-argparse (setup.py): started
  Building wheel for sphinx-argparse (setup.py): finished with status 'done'
  Created wheel for sphinx-argparse: filename=sphinx_argparse-0.2.5-py3-none-any.whl size=11549 sha256=a6cd6938c3c655193f230e0181f48d037539475be6989b7f17d59760167f5c54
  Stored in directory: /tmp/pip-ephem-wheel-cache-s8zdxc9_/wheels/4a/4c/12/83c88bdc1bc352d7036de2891b5d6729adcf1bda3bab015560
Successfully built sphinx-argparse
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 191, in get_installation_order
    weights = get_topological_weights(graph)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-semver/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 242, in get_topological_weights
    assert len(weights) == len(graph)
AssertionError
```

# Suggested Solution

Fix the problem.

@tlaferriere Thomas, do you know what can be the problem?

**Comment by tomschr** [comment]
That wasn't the problem. @scls19fr Do you have any idea?

In the "Advanced Settings" menue in RTD admin, I've tried "Install Project" and "Use system packages". I also switch to the "CPython 3.x" interpreter. All to no avail.

**Comment by tlaferriere** [comment]
I just came across this issue pypa/pip#9031 opened 5 days ago. It appears to be a bug in pip that happens when installing Sphinx and friends. Maybe downgrading pip would fix it 🤔?

**Comment by tlaferriere** [comment]
Actually I read a bit more, and it seems removing Sphinx from the required packages is a good workaround. It should still get installed because the plugins depend on it.

**Comment by tlaferriere** [comment]
Actually I read a bit more, and it seems removing Sphinx from the required packages is a good workaround. It should still get installed because the plugins depend on it.

**Comment by tomschr** [comment]
Thank you very much Thomas!

**Comment by tomschr** [comment]
It worked! :tada: :+1: The latest doc is now online! Thanks Thomas!
