### ISSUE TITLE
Problem building the package

### ISSUE THREAD

**Issue by apirogov** [python-semver/python-semver#397]
when trying to install newest version (commit `ff34cce`) I get:

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/local/home/a.pirogov/.local/share/virtualenvs/irdm-dev-e7pFVQEY/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/local/home/a.pirogov/.local/share/virtualenvs/irdm-dev-e7pFVQEY/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/local/home/a.pirogov/.local/share/virtualenvs/irdm-dev-e7pFVQEY/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/local/home/a.pirogov/.local/share/virtualenvs/irdm-dev-e7pFVQEY/lib/python3.9/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 881, in parse_config_files
          setupcfg.parse_configuration(
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 163, in parse_configuration
          options.parse()
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 508, in parse
          section_parser_method(section_options)
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 482, in parse_section
          self[name] = value
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py", line 290, in __setitem__
          value = parser(value)
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 711, in __init__
          parsed.add(Specifier(specifier))
        File "/tmp/pip-build-env-gnvw110t/overlay/lib/python3.9/site-packages/setuptools/_vendor/packaging/specifiers.py", line 245, in __init__
          raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.7.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This is fixed when using `python_requires = >=3.7` (removing the `*`)

**Comment by tomschr** [comment]
Thanks @apirogov for your report! Much appreciated! :+1: 

That's interesting, I never had this problem. Neither in said commit ff34cce and also not for HEAD.

You seem to have used a virtual env. Could you tell me the steps you used? I would like to reproduce that on my machine.

Thanks!

**Comment by apirogov** [comment]
I reproduced this in a fresh venv created with `python -m venv` (on Python 3.8.15, installed using `pyenv`)

and in the venv running: 
```bash
pip install git+ssh://git@github.com/python-semver/python-semver.git@ff34cce
```

Happens with `pip` 22.0.4 and also 23.0.1, and it uses `setuptools` 56.0.0

**Comment by tomschr** [comment]
Thanks @apirogov for your test efforts. If I'm not mislead, I saw this asterisk syntax somewhere else.

Well, it's fixed now so you can use it with any errors. I hope I can build the RC release this week.

Many thanks!

**Comment by apirogov** [comment]
Thanks for the quick reaction :-)
